// Every user-visible string lives here so the UI can be translated later.
export const strings = {
  appName: 'Language Exchange',
  common: {
    save: 'Save',
    cancel: 'Cancel',
    next: 'Next',
    done: 'Done',
    loading: 'Loading…',
    retry: 'Try again',
    optional: 'optional',
  },
  auth: {
    signInTitle: 'Sign in',
    signUpTitle: 'Create account',
    email: 'Email',
    password: 'Password',
    passwordHint: 'At least 8 characters',
    signIn: 'Sign in',
    signUp: 'Create account',
    noAccount: 'New here? Create an account',
    haveAccount: 'Already have an account? Sign in',
    ageConfirm: 'I am 18 years old or older',
    termsPrefix: 'I accept the ',
    terms: 'Terms of Service',
    and: ' and the ',
    privacy: 'Privacy Policy',
    invalidEmail: 'Enter a valid email address.',
    shortPassword: 'The password must be at least 8 characters.',
    mustConfirmAge: 'You must be 18 or older to use this app.',
    mustAcceptTerms: 'Please accept the Terms of Service and Privacy Policy.',
    checkEmail: 'Check your email and tap the confirmation link, then sign in.',
  },
  onboarding: {
    aboutTitle: 'About you',
    nameLabel: 'Display name',
    namePlaceholder: 'How partners will see you',
    bioLabel: 'Short bio',
    bioPlaceholder: 'Where you are, what you like, when you can chat…',
    nameRequired: 'Please enter a display name.',
    speakTitle: 'Languages I speak',
    speakHelp:
      'Pick the languages you can help someone practise. Mark the ones you grew up with as native.',
    native: 'Native speaker',
    speakRequired: 'Pick at least one language you speak.',
    learnTitle: 'Languages I am learning',
    learnHelp: 'Pick what you want to practise and your current level.',
    learnRequired: 'Pick at least one language you are learning.',
    levelRequired: 'Choose a level for every language you are learning.',
    finish: 'Finish',
  },
  levels: {
    A1: 'A1 · Beginner',
    A2: 'A2 · Elementary',
    B1: 'B1 · Intermediate',
    B2: 'B2 · Upper intermediate',
    C1: 'C1 · Advanced',
    C2: 'C2 · Proficient',
  },
  tabs: {
    home: 'Home',
    profile: 'Profile',
  },
  home: {
    greeting: (name: string) => `Hi ${name}!`,
    comingSoon: 'Finding partners arrives in the next phase. For now, make sure your profile is complete.',
    speaks: 'You speak',
    learning: 'You are learning',
  },
  profile: {
    title: 'Profile',
    edit: 'Edit profile',
    signOut: 'Sign out',
    deleteAccount: 'Delete account',
    deleteConfirmTitle: 'Delete your account?',
    deleteConfirmBody:
      'This permanently removes your profile, languages and messages. It cannot be undone.',
    deleteConfirmButton: 'Delete',
    timezone: 'Timezone',
    speaks: 'Speaks',
    learning: 'Learning',
    noBio: 'No bio yet.',
    nativeTag: 'native',
  },
  editProfile: {
    title: 'Edit profile',
    changePhoto: 'Change photo',
    removePhoto: 'Remove photo',
    useDeviceTimezone: 'Use device timezone',
  },
  legal: {
    termsTitle: 'Terms of Service',
    privacyTitle: 'Privacy Policy',
    draftNotice: 'Draft for development. The final text will be published before launch.',
  },
  banned: {
    title: 'Account suspended',
    body: 'This account has been suspended for breaking the community rules.',
  },
  errors: {
    generic: 'Something went wrong. Please try again.',
  },
} as const;
