// Every user-visible string lives here so the UI can be translated later.
export const strings = {
  appName: 'Language Exchange',
  common: {
    save: 'Save',
    cancel: 'Cancel',
    next: 'Next',
    done: 'Done',
    loading: 'Loading…',
    retry: 'Try again',
    optional: 'optional',
  },
  auth: {
    signInTitle: 'Sign in',
    signUpTitle: 'Create account',
    email: 'Email',
    password: 'Password',
    passwordHint: 'At least 8 characters',
    signIn: 'Sign in',
    signUp: 'Create account',
    noAccount: 'New here? Create an account',
    haveAccount: 'Already have an account? Sign in',
    ageConfirm: 'I am 18 years old or older',
    termsPrefix: 'I accept the ',
    terms: 'Terms of Service',
    and: ' and the ',
    privacy: 'Privacy Policy',
    invalidEmail: 'Enter a valid email address.',
    shortPassword: 'The password must be at least 8 characters.',
    mustConfirmAge: 'You must be 18 or older to use this app.',
    mustAcceptTerms: 'Please accept the Terms of Service and Privacy Policy.',
    checkEmail: 'Check your email and tap the confirmation link, then sign in.',
  },
  onboarding: {
    aboutTitle: 'About you',
    nameLabel: 'Display name',
    namePlaceholder: 'How partners will see you',
    bioLabel: 'Short bio',
    bioPlaceholder: 'Where you are, what you like, when you can chat…',
    nameRequired: 'Please enter a display name.',
    learnTitle: 'What do you want to practise?',
    learnHelp: 'Pick the languages you are learning and how far along you are.',
    learnRequired: 'Pick at least one language to practise.',
    levelRequired: 'Choose a level for every language you are practising.',
    teachTitle: 'What can you help with?',
    teachHelp:
      'Pick the languages you speak well enough to help a partner practise. Mark your mother tongue as native.',
    native: 'This is my native language',
    teachRequired: 'Pick at least one language you can help with.',
    pickedAsLearning: 'You are practising this one',
    pickedAsTeaching: 'You are helping with this one',
    finish: 'Finish',
  },
  levels: {
    beginner: { title: 'Beginner', help: 'I know some words and simple phrases.' },
    intermediate: { title: 'Intermediate', help: 'I can have a simple conversation.' },
    advanced: { title: 'Advanced', help: 'I can talk about most topics comfortably.' },
  },
  tabs: {
    home: 'Home',
    profile: 'Profile',
  },
  home: {
    greeting: (name: string) => `Hi ${name}!`,
    comingSoon: 'Finding partners arrives in the next phase. For now, make sure your profile is complete.',
    speaks: 'You can help with',
    learning: 'You are practising',
  },
  profile: {
    title: 'Profile',
    edit: 'Edit profile',
    signOut: 'Sign out',
    deleteAccount: 'Delete account',
    deleteConfirmTitle: 'Delete your account?',
    deleteConfirmBody:
      'This permanently removes your profile, languages and messages. It cannot be undone.',
    deleteConfirmButton: 'Delete',
    timezone: 'Timezone',
    speaks: 'Helps with',
    learning: 'Practising',
    noBio: 'No bio yet.',
    nativeTag: 'native',
  },
  editProfile: {
    title: 'Edit profile',
    changePhoto: 'Change photo',
    removePhoto: 'Remove photo',
    useDeviceTimezone: 'Use device timezone',
  },
  legal: {
    termsTitle: 'Terms of Service',
    privacyTitle: 'Privacy Policy',
    draftNotice: 'Draft for development. The final text will be published before launch.',
  },
  banned: {
    title: 'Account suspended',
    body: 'This account has been suspended for breaking the community rules.',
  },
  errors: {
    generic: 'Something went wrong. Please try again.',
  },
} as const;
